version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bookmora_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookmora_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: mora1812/bookmora-backend:latest
    container_name: bookmora_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bookmora_network

  frontend:
    image: mora1812/bookmora-frontend:latest
    container_name: bookmora_frontend
    restart: unless-stopped
    networks:
      - bookmora_network

  nginx:
    image: nginx:alpine
    container_name: bookmora_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - bookmora_network

volumes:
  postgres_data:

networks:
  bookmora_network:
    driver: bridge
